LOAD DATA
INFILE 'D:\Learning_journy\SQL_PL_SQL\Learning_programs\Oracle\SQL\CSV_files\cities100.csv'
TRUNCATE
INTO TABLE cities_usa
FIELDS TERMINATED BY ","
(USPS, GEOID, ANSICODE, NAME, LSAD, FUNCSTAT, POP10, HU10, ALAND, AWATER, ALAND_SQMI, AWATER_SQMI, INTPTLAT, INTPTLONG)