LOAD DATA
INFILE 'D:\Learning_journy\SQL_PL_SQL\Learning_programs\Oracle\SQL\CSV_files\us_500.csv'
TRUNCATE INTO TABLE usa_temp
FIELDS TERMINATED BY ","
(
FIRST_NAME,
LAST_NAME,
COMPANY_NAME,
ADDRESS,
CITY,
COUNTY,
STATE,
ZIP,
PHONE1,
PHONE2,
EMAIL,
WEB
)